services:

  postgres:
    image: postgres:17.4
    container_name: zeppelin-order-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zeppelin

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - zeppelin

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=${REDIS_HOSTS}
    ports:
      - 8081:8081
    networks:
      - zeppelin

networks:
  zeppelin:
    driver: "bridge"